# Generated by Django 6.0.5 on 2026-05-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Müəllif')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='Məqalə')),
            ],
            options={
                'verbose_name': 'Şərh',
                'verbose_name_plural': 'Şərhləri',
                'ordering': ['-created_date'],
            },
        ),
    ]
