# Generated by Django 6.0.5 on 2026-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_comment_options_alter_comment_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Etiket Adı')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketlər',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article.tag', verbose_name='Etiketlər'),
        ),
    ]
